config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  
  resources :users, only: [:show] do
    resources :messages, only: [:index, :create, :show, :new, :destroy]
  end

  resources :proposals

  resources :schools

  get 'schools/:id/link_form' => 'schools#link_form', as: :school_link_form

  get 'schools/:id/create_link/:proposal_id' => 'schools#create_link', as: :school_create_link

  get 'proposals/:id/link_form' => 'proposals#link_form', as: :proposal_link_form

  get 'proposals/:id/create_link/:school_id' => 'proposals#create_link', as: :proposal_create_link

  root 'welcome#index'

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :proposals, :dependent => :delete_all
  has_many :schools, :dependent => :delete_all
  has_many :messages

  has_attached_file :photo, styles: { medium: "300x300#", thumbnail: "100x100#" },
                  :bucket => 'volunteach',
                  :url  => "/assets/users/:id/:style/:basename.:extension",
                  :path => ":rails_root/public/assets/users/:id/:style/:basename.:extension"
  
 validates_attachment_content_type :photo, :content_type => /\Aimage/
  # Validate filename
  validates_attachment_file_name :photo, :matches => [/png\Z/, /jpe?g\Z/]
  # Explicitly do not validate
  do_not_validate_attachment_file_type :photo 

  geocoded_by :location
  after_validation :geocode

end

app/controllers/users/confirmations_controller.rb
class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/passwords_controller.rb
class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
# before_filter :configure_sign_up_params, only: [:create]
# before_filter :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  protected

  #If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.for(:sign_up) << :name
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.for(:account_update) << :name
  # end

  # private

  # def sign_up_params
  #   params.require(:user).permit(:username, :name, :location, :category)
  # end

  # def account_update_params
  #   params.require(:user).permit(:username, :name, :location, :category)
  # end 

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
# before_filter :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.for(:sign_in) << :attribute
  # end
end

app/controllers/users/unlocks_controller.rb
class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	def show
		@user = User.find(params[:id])
		@proposals = Proposal.where(user: @user)
		@schools = School.where(user: @user)
		@messages_received = Message.where(receiver_id: @user)
		@messages_sent = Message.where(sender_id: @user)
	end

	private 
	def user_params
		params.require(:user).permit(:username, :email, :password, :name, :location, :password_confirmation, :photo)
	end
end

app/views/users/show.html.erb
<div class="container">
	<div class="row text-center">

		<% if @user.photo? %>
				<%= image_tag @user.photo.url(:medium) %>
			<% else %>
				<i class="fa fa-user fa-2x"></i>
			<% end %>

		<% if @user.category == "volunteer" %>
	</div>
	<div class="row text-center">
			<h1><%= @user.name %> | <%= @user.location %></h1>
			<hr>
	</div>
			<h2>Class Proposals</h2>
				<% @proposals.each do |proposal| %>
					<%= render 'proposals/proposal_show', proposal: proposal %>
				<% end %>
		<% end %>

		<% if @user.category == "school" %>
			<h1> <%= @user.name %> | <%= @user.location %></h1>
			</div>
			<hr>
			<h2>Schools added by this user:</h2>
				<% @schools.each do |school| %>
					<div class="panel panel-default">
						<div class="panel body">
							<div class="container">
								<h4 style = "display: inline-block"><%= school.school_name %></h4>
								<span style="float: right">
									<% if current_user.category == "volunteer" %>
									<%= link_to 'I Taught At this School', school_link_form_path(school), class: "btn btn-dark" %> <% end %><%= link_to 'View', school_path(school), class: "btn btn-dark" %></span>
								</h4>
								<p>Location: <%= school.location %></p>
								<h5><strong>School Needs: <%= school.needs %></strong></h5>
								<p>Students' Age: <%= school.students_age %></p>
								<% if current_user == school.user %>
									<%= link_to 'Edit', edit_school_path(school), class: "btn btn-default" %>
									<%= link_to 'Delete', school_path(school), method: :delete, data: {confirm: 'Are you sure you want to delete this school?'}, class: "btn btn-default" %>
								<% end %>
							</div>
						</div>
					</div>
				<% end %>
		<% end %>

		<% if current_user == @user %>
			<h1>Messages</h1>
			<span style="float: right; margin-top: 10px;"><%= link_to 'Send a New Message', new_user_message_path(current_user), class: "btn btn-default" %></span>
			<h2>Inbox <i class="fa fa-inbox"></i></h2>
			<% if @messages_received.empty? %>
				<h4>You have not received any messages yet.</h4>
			<% else %>
				<% @messages_received.each do |message| %>
					<%= render 'messages/inbox', message: message, out: false %>
				<% end %>
			<% end %>

			<h2>Messages Sent</h2>
			<% if @messages_sent.empty? %>
				<h4>You have not sent any messages yet.</h4>
			<% else %>
				<% @messages_sent.each do |message| %>
					<%= render 'messages/inbox', message: message, out: true %>
				<% end %>
			<% end %>
		<% end %>
	</div>
</div>

		