config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  
  resources :users, only: [:show] do
    resources :messages, only: [:index, :create, :show, :new, :destroy]
  end

  resources :proposals

  resources :schools

  get 'schools/:id/link_form' => 'schools#link_form', as: :school_link_form

  get 'schools/:id/create_link/:proposal_id' => 'schools#create_link', as: :school_create_link

  get 'proposals/:id/link_form' => 'proposals#link_form', as: :proposal_link_form

  get 'proposals/:id/create_link/:school_id' => 'proposals#create_link', as: :proposal_create_link

  root 'welcome#index'

end

app/models/proposal.rb
class Proposal < ActiveRecord::Base
	has_and_belongs_to_many :schools
	belongs_to :user

	validates :topic, :language, :description, presence: true
end

app/controllers/proposals_controller.rb
class ProposalsController < ApplicationController
	before_action :authenticate_user!
	def index
		@query = params[:query]

		if @query
			@proposals = Proposal.advanced_search(@query)
		else
			@proposals = Proposal.all
		end
	end

	def show
		@proposal  = Proposal.find(params[:id])
		@message = Message.new
		@receiver = @proposal.user.name
	end

	def search
		@query = params[:query]
		@proposals = Proposal.advanced_search(@query)
	end

	def edit
		@proposal = Proposal.find(params[:id])

		if(current_user != @proposal.user)
			redirect_to proposal_path(@proposal), alert:"You can't edit this proposal."
		end
	end

	def link_form
		@proposal = Proposal.find(params[:id])
		@schools = School.all
	end

	def create_link
		@proposal = Proposal.find(params[:id])
		@school = School.find(params[:school_id])
		if !@proposal.schools.include?(@school)
			@proposal.schools << @school
		end

		redirect_to proposal_path(@proposal)
	end

	def update
		@proposal = Proposal.find(params[:id])

		if @proposal.update(proposal_params)
			redirect_to proposal_path(@proposal)
		else
			render :edit
		end
	end

	def new
		@proposal = Proposal.new

		if current_user.category == "school"
			redirect_to proposals_path, alert: "Sorry, you can't add a proposal because
			your user is of type school. However, you can add a class to your needs by 
			editing your school."
		end
	end

	def create 
		@proposal = current_user.proposals.build(proposal_params
			)

		if @proposal.save
			redirect_to proposal_path(@proposal)
		else
			render :new
		end
	end

	def destroy
		@proposal = Proposal.find(params[:id])

		if(current_user != @proposal.user)
			redirect_to proposal_path(@proposal), alert: "You can't delete this proposal."
		end
		
		@proposal.destroy

		redirect_to proposals_path
	end

	private 
	def proposal_params
		params.require(:proposal).permit(:description, :topic, :duration, :target_age, :language, :user_id)
	end
end

app/views/proposals/_proposal.html.erb
<h4><%= proposal.topic %></h4>
<p><%= proposal.description %></p>

app/views/proposals/_proposal_form.html.erb
<% if @proposal.errors.present? %>
	<% @proposal.errors.full_messages.each do |msg| %>
		<p><%= msg %></p>
	<% end %>
<% end %>

<div class="container">
	<div class="row">
		<div class="col-md-6">
			<%= simple_form_for(@proposal, html: { class: 'form-horizontal' }) do |form| %>
			<p>
				<%= form.input :topic, placeholder: "Topic" %>
			</p>
			<p>
				<%= form.input :duration, label: "Class Duration", placeholder: "Class Duration" %>
			</p>
			<p>
				<%= form.input :target_age, placeholder: "Target age group"%>
			</p>
			<p>
				<%= form.input :language, label: "Language(s)" %>
			</p>
			<p>
				<%= form.input :description, as: :text %>
			</p>
			<p>
				<%= form.submit "Create Proposal", class: "btn btn-dark btn-lg" %>
			</p>
			<% end %>
		</div>
	</div>
</div>

app/views/proposals/_proposal_show.html.erb
<div class="container">
	<div class="row">
		<div class="col-md-1">
			<% if proposal.user.photo? %>
				<%= image_tag proposal.user.photo.url(:thumbnail) %>
			<% else %>
				<i class="fa fa-book fa-4x"></i>
			<% end %>
		</div>

		<div class="col-md-10", style="margin-left:30px">

			<div class="panel panel-default">
				<div class="panel body">
					<span class="pull-right", style="margin-right: 5px;"><%= link_to 'View', proposal_path(proposal), class: "btn btn-dark" %></span>
					<div class="container", style="font-size: 18px">
						<h3><%= proposal.topic %></h3>

						<p>Taught by: <%= link_to proposal.user.name, user_path(proposal.user) %></p>
						<p>Description: <%= proposal.description %></p>
						<p>Location: <%= proposal.user.location %></p>
						<% if current_user == proposal.user %>
							<%= link_to 'Edit', edit_proposal_path(proposal), class: "btn btn-dark" %>
							<%= link_to 'Delete', proposal_path(proposal), method: :delete, data: {confirm: 'Are you sure you want to delete this proposal?'}, class: "btn btn-dark" %>
							<%= link_to 'I Have Taught this Class', proposal_link_form_path(proposal), class: "btn btn-dark" %>
						<% end %>
					</div>
				</div>
			</div>
		</div>

	</div>
</div>

app/views/proposals/edit.html.erb
<div class="container">
<h1>Edit This Class Proposal</h1>


	<%= render 'proposal_form' %>


<%= link_to 'Back', proposals_path %>
</div>

app/views/proposals/index.html.erb
<div class='container'>
	<div class='row'>
		<% if current_user.category == "volunteer" %>
			<span style="float: right; margin-top: 20px;"><%= link_to 'Add a New Proposal', new_proposal_path, class: "btn btn-default btn-lg" %></span>
		<% end %>
		<% near = User.near([current_user.latitude, current_user.longitude], 20) %>
		<h1>Class Proposals from users near you:</h1>
		<% if near.empty? %>
			<h3>Sorry, no users have added class proposals near you</h3>
		<% else %>
			<% near.each do |user|%>
				<% user.proposals.each do |proposal| %>
					<%= render 'proposal_show', proposal: proposal %>
				<% end %>
			<% end %>
		<% end %>
		<hr>
	</div>


<h1>All Class Proposals</h1>
	<div class="container">
		<div class="row">
			<div class="col-md-10">
				<%= form_tag(proposals_path, method: "get", html: { class: 'form-inline' }) do %>
				<%= label_tag(:query, "Search All Proposals:") %>
				<%= text_field_tag :query, params[@query], placeholder: "Topic, Description, Target Age, etc.", input_html: { maxlength: 30 } %>
				<%= submit_tag "Search", class: "btn btn-default" %>
				<% end %>
				<br>
			</div>
		</div>
	</div>

	<div class="row">
		<% @proposals.each do |proposal| %>
			<%= render 'proposal_show', proposal: proposal %>
		<% end %>
	</div>
</div>

app/views/proposals/link_form.html.erb
<div class= "container">
	<h1>Select the school in which you taught a(n) <%= @proposal.topic %> class:</h1>
	
	<% @schools.each do |school| %>
		<h3><%= school.school_name %></h3>
		<p><%= school.location %><p>
		<%= link_to 'Select this school', proposal_create_link_path(@proposal, school), class: "btn btn-default" %>
	<% end %>

</div>

app/views/proposals/new.html.erb
<div class="container">
	<h1>Create a New Class Proposal!</h1>

	<%= render 'proposal_form' %>
</div>

app/views/proposals/show.html.erb
<div class="container">
	<div class='row'>
		<div class="col-md-4" style="margin-top: 15px;">
			<% if @proposal.user.photo? %>
				<%= image_tag @proposal.user.photo.url(:medium) %>
			<% else %>
				<i class="fa fa-book fa-4x"></i>
			<% end %>
		</div>

		<div class="col-md-8">
			<h2><%= @proposal.topic %></h2>
			<p>Taught by: <%= link_to @proposal.user.name, user_path(@proposal.user) %></p>
			<div class="well", style="font-size: 20px">
				<p>Description: <%= @proposal.description %></p>
				<p>Location: <%= @proposal.user.location %></p>
				<p>Class Duration: <%= @proposal.duration %></p>
				<p>Target Age: <%= @proposal.target_age %></p>
				<p>Languages: <%= @proposal.language %></p>
			</div>
		</div>
		<hr>
	</div>

	<div class="row">
		<h2>Schools where this class has been taught</h2>
		<% if @proposal.schools == [] %>
			<h3>This class has not been taught at any schools yet.</h3>
		<% else %> 
			<% @proposal.schools.each do |school| %>
				<%= render 'schools/school_show', school: school %>
			<% end %>
		<% end %><hr>
	</div>

		<div class="row">
			<div class="col-md-1">
				<i class="fa fa-envelope-o fa-4x"></i><br>
			</div>
			<div class="col-md-10">
				<%= form_for ([current_user, @message]) do |f| %>

					<p>
					  <%= f.label "To" %><br>
					  <%= f.text_field :receiver_id, :value => @receiver %></p>
					<p>
					  <%= f.label "Subject" %><br>
					  <%= f.text_field :title %>
					</p>
					<p>
					  <%= f.label :message %><br>
					  <%= f.text_area :body %>
					</p>
					<p>
					  <%= f.submit "Send Message", class: "btn btn-dark" %>
					</p>
				<% end %>
			<h4><em> Send a message to the volunteer</em></h4>
			</div>
		</div>

		
		<div class="row">
		<%= link_to 'Back', proposals_path, class: "btn btn-dark" %>
		<% if current_user == @proposal.user %>
			<%= link_to 'Edit', edit_proposal_path(@proposal), class: "btn btn-dark" %>
			<%= link_to 'Delete', proposal_path(@proposal), method: :delete, data: {confirm: 'Are you sure you want to delete this proposal?'}, class: "btn btn-dark" %>
		<% end %>
		</div>
	</div>