config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  
  resources :users, only: [:show] do
    resources :messages, only: [:index, :create, :show, :new, :destroy]
  end

  resources :proposals

  resources :schools

  get 'schools/:id/link_form' => 'schools#link_form', as: :school_link_form

  get 'schools/:id/create_link/:proposal_id' => 'schools#create_link', as: :school_create_link

  get 'proposals/:id/link_form' => 'proposals#link_form', as: :proposal_link_form

  get 'proposals/:id/create_link/:school_id' => 'proposals#create_link', as: :proposal_create_link

  root 'welcome#index'

end

app/models/school.rb
class School < ActiveRecord::Base
	has_and_belongs_to_many :proposals
	belongs_to :user
	geocoded_by :location
	after_validation :geocode

	validates :school_name, :location, :needs, presence: true
end

app/controllers/schools_controller.rb
class SchoolsController < ApplicationController
	before_action :authenticate_user!
	def index
		@query = params[:query]

		if @query
			@schools = School.advanced_search(@query)
		else
			@schools = School.all
		end
	end

	def search
		@query = params[:query]
		@schools = School.advanced_search(@query)
	end

	def show
		@school  = School.find(params[:id])
		@proposals = @school.proposals
		@receiver = @school.user.name
		@message = Message.new
	end	

	def edit
		@school = School.find(params[:id])

		if(current_user != @school.user)
			redirect_to school_path(@school), alert:"You can't edit this school."
		end
	end

	def update
		@school = School.find(params[:id])

		if @school.update(school_params)
			redirect_to school_path(@school)
		else
			render :edit
		end
	end

	def new
		@school = School.new

		if current_user.category == "volunteer"
			redirect_to schools_path, alert: "You can't add a school because your user is of type volunteer."
		end
	end

	def create 
		@school = current_user.schools.build(school_params)

		if @school.save
			redirect_to school_path(@school)
		else
			render :new
		end
	end

	def create_link
		@school = School.find(params[:id])
		@proposal = Proposal.find(params[:proposal_id])
		if !@school.proposals.include?(@proposal)
			@school.proposals << @proposal
		end

		redirect_to school_path(@school)
	end

	def destroy
		@school = School.find(params[:id])

		if(current_user != @school.user)
			redirect_to school_path(@school), alert: "You can't delete this school."
		end
		
		@school.destroy

		redirect_to schools_path
	end

	def link_form
		@school = School.find(params[:id])
		@proposals = current_user.proposals
	end

	private
	def school_params
		params.require(:school).permit(:school_name, :location, :needs, :students_age)
	end
end

app/views/schools/_school_form.html.erb
<% if @school.errors.present? %>
	<% @school.errors.full_messages.each do |msg| %>
		<p><%= msg %></p>
	<% end %>
<% end %>

<div class="container">
	<div class="row">
		<div class="col-md-6">

			<%= simple_form_for @school do |f| %>
			<p>
				<%= f.input :school_name, placeholder: "The name of your institution" %>
			</p>
			<p>
				<%= f.input :location, label: "Address", placeholder: "Address" %>
			</p>
			<p>
				<%= f.input :needs, placeholder: "Teacher or educational needs" %>
			</p>
			<p>
				<%= f.input :students_age, label: "Students' Age", placeholder: "Students' age range" %>
			</p>

			<p>
				<%= f.submit "Create School", class: "btn btn-dark btn-lg" %>
			</p>
			<% end %>
					<%= link_to 'Back', schools_path %>
		</div>
	</div>
</div>

app/views/schools/_school_search.html.erb
<%= form_tag(schools_path, method: "get") do %>
  <%= label_tag(:query, "Search All Schools:") %>
  <%= text_field_tag :query, params[@query], placeholder: "Name, Location, Need" %>
  <%= submit_tag "Search", class: "btn btn-default" %>
<% end %><br>

app/views/schools/_school_show.html.erb
<div class="container">
	<div class="row">
		<div class="col-md-1">
			<% if school.user.photo? %>
				<%= image_tag school.user.photo.url(:thumbnail) %>
			<% else %>
				<i class="fa fa-bus fa-4x"></i>
			<% end %>
		</div>




		<div class="col-md-10", style="margin-left:30px">
			<div class="panel panel-default">
				<div class="panel body">
					<span class="pull-right", style="margin-right: 5px"><%= link_to 'View', school_path(school), class: "btn btn-dark" %></span>
						<div class="container">
							<h4 style = "display: inline-block"><%= school.school_name %></h4>
								
							<p>Location: <%= school.location %></p>
							<p>Added by <%= link_to school.user.name, user_path(school.user) %></p>
								<% if current_user == school.user %>
									<%= link_to 'Edit', edit_school_path(school), class: "btn btn-default" %>
									<%= link_to 'Delete', school_path(school), method: :delete, data: {confirm: 'Are you sure you want to delete this school?'}, class: "btn btn-default" %>
								<% end %>
							<% if current_user.category == "volunteer" %>
								<%= link_to 'I Taught At this School', school_link_form_path(school), class: "btn btn-dark" %> 
							<%end %>
						</div>
				</div>
			</div>
		</div>
	</div>
</div>

app/views/schools/edit.html.erb
<div class="container">
<h1>Edit this School</h1>

<%= render 'school_form' %>

</div>

app/views/schools/index.html.erb
<div class='container'>
<div class='row'>
<% if current_user.category == "school" %>
	<span style="float: right; margin-top: 20px;"><%= link_to 'Add a New School', new_school_path, class: "btn btn-default btn-lg" %></span>
<% end %>
<% near = School.near([current_user.latitude, current_user.longitude], 20) %>
<h1>Schools in Need Near You</h1>
<% if near.empty? %>
	<h3>Sorry, there are no schools near you yet</h3>
<% else %>
	<% near.each do |school| %>
		<%= render 'schools/school_show', school: school %>
	<% end %>
<% end %>
<hr>

<h1>All Schools in Need</h1>
	<%= render 'school_search' %>

<% @schools.each do |school| %>
	<%= render 'schools/school_show', school: school %>
<% end %>

app/views/schools/link_form.html.erb
<div class= "container">
	<h1>Select the class which you taught at <%= @school.school_name %>:</h1>
	
	<% @proposals.each do |proposal| %>
		<h3><%= proposal.topic %></h3>
		<p><%= proposal.description %><p>
		<%= link_to 'Select this class', school_create_link_path(@school, proposal), class: "btn btn-default" %>
	<% end %>

</div>

app/views/schools/new.html.erb
<div class="container">
	<h1>Add a School</h1>

	<%= render 'school_form' %>
	
</div>

app/views/schools/show.html.erb
<div class="container">
	<div class="row">
		<div class="col-md-4", style="padding-top: 50px">
			<div style="text-align: center">
				<% if @school.user.photo? %>
					<%= image_tag @school.user.photo.url(:medium) %>
				<% else %>
					<i class="fa fa-bus fa-4x"></i>
				<% end %>
			</div>
		</div>
		<div class="col-md-5">
			<h2><%= @school.school_name %></h2>
			<h3>Needs: <%= @school.needs %></h3>
			<p>Students' Age: <%= @school.students_age %></p>
		</div>
		<div class="col-md-4" style="padding-top: 10px">
			
			<h3><span class="pull-right"><%= @school.location %></span></h3>
		</div>
	</div>
	<div class="row">
		<div class="col-md-12">
			<% if current_user == @school.user %>
				<br><%= link_to 'Edit', edit_school_path(@school), class: "btn btn-dark" %>
				<%= link_to 'Delete', @school, :method => :delete, :confirm => "Are you sure?", class: "btn btn-dark" %>
			<% end %>
		</div>
	</div>

		<h2>Classes previously taught at this school:</h2>
		<% if @proposals == [] %>
			<h3>No classes have been taught at this school yet.</h3>
		<% else %>
			<% @proposals.each do |proposal| %>
			<%= render 'proposals/proposal_show', proposal: proposal %>
			<% end %>
		<% end %><hr>
	<div class="row">
			<div class="col-md-1">
				<i class="fa fa-envelope-o fa-4x"></i><br>
			</div>
			<div class="col-md-10">
			<%= form_for ([current_user, @message]) do |f| %>

					<p>
					  <%= f.label "To" %><br>
					  <%= f.text_field :receiver_id, :value => @receiver %></p>
					<p>
					  <%= f.label "Subject" %><br>
					  <%= f.text_field :title %>
					</p>
					<p>
					  <%= f.label :message %><br>
					  <%= f.text_area :body %>
					</p>
					<p>
					  <%= f.submit "Send Message", class: "btn btn-dark" %>
					</p>
				<% end %>
			<h4><em> Send a message to request to teach at the school</em></h4>
		

				<p><%= link_to 'Back', schools_path, class: "btn btn-dark" %></p>
		</div>
	</div>
</div>