config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  
  resources :users, only: [:show] do
    resources :messages, only: [:index, :create, :show, :new, :destroy]
  end

  resources :proposals

  resources :schools

  get 'schools/:id/link_form' => 'schools#link_form', as: :school_link_form

  get 'schools/:id/create_link/:proposal_id' => 'schools#create_link', as: :school_create_link

  get 'proposals/:id/link_form' => 'proposals#link_form', as: :proposal_link_form

  get 'proposals/:id/create_link/:school_id' => 'proposals#create_link', as: :proposal_create_link

  root 'welcome#index'

end

app/views/layouts/_alerts.erb
<% if notice %>
  <p class="alert alert-success"><%= notice %></p>
<% end %>
<% if alert %>
  <p class="alert alert-danger"><%= alert %></p>
<% end %>

app/views/layouts/_alerts.html.erb
<% if notice %>
  <p class="alert alert-success"><%= notice %></p>
<% end %>
<% if alert %>
  <p class="alert alert-danger"><%= alert %></p>
<% end %>

app/views/layouts/_nav.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" >
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">VolunTeach</a>
    </div>

    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><a href="/">Home</a></li>
        <% if user_signed_in? %>
          <li><%= link_to 'Proposals', proposals_path %></li>
          <li><%= link_to 'Schools', schools_path %></li>
          <li><%= link_to 'My Profile', user_path(current_user) %></li>
        <% end %>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li>
        	<% if user_signed_in? %>
			  <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %>
		</li>
		<li>
			  <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
		</li>
			<% else %>
		<li>
			  <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %>
		</li>
		<li>
			  <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
		</li>
			<% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/_nav.html.erb
<nav class="navbar navbar-default">
  <div class="container fluid">

    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
    </div>

    <div  id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <ul class="nav navbar-nav navbar-left">
            <li><a class="navbar-link", href="/">VolunTeach</a></li>
              
            <li>
                <a href="#about">About</a>
            </li>

          <% if user_signed_in? %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">Browse <b class="caret"></b></a>
            <ul class="dropdown-menu">
              <li><%= link_to 'Proposals', proposals_path %></li>
              <li><%= link_to 'Schools', schools_path %></li>
              <li><%= link_to 'My Profile', user_path(current_user) %></li>
            </ul>
          </li>
          <% end %>
        </ul>

        <ul class="nav navbar-nav navbar-right">
            <li>
              	<% if user_signed_in? %>
      			  <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %>
        		</li>
        		<li>
        			  <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
        		</li>
        			<% else %>
        		<li>
        			  <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %>
        		</li>
        		<li>
        			  <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
        		</li>
  			   <% end %>
        </ul>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>VolunTeach</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css">
  
  <link href='https://fonts.googleapis.com/css?family=Source+Sans+Pro:400,300,300italic,400italic,700,700italic' rel='stylesheet' type='text/css'>

  <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
  <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
</head>
<body>

<%= render 'layouts/alerts' %>

<%= render 'layouts/nav' %>

<%= yield %>

<footer>
        <hr><div class="container">
            <div class="row">
                <div class="col-lg-10 col-lg-offset-1 text-center">
                    <h4><strong>Contact Us:</strong>
                    </h4>
                    <ul class="list-unstyled">
                        <li><i class="fa fa-phone fa-fw"></i> +1 (907) 223 0466</li>
                        <li><i class="fa fa-envelope-o fa-fw"></i>  <a href="mailto:mariamclaughlin@college.harvard.edu">mariamclaughlin@college.harvard.edu</a>
                        </li>
                        <li><i class="fa fa-envelope-o fa-fw"></i>  <a href="mailto:nadin@stanford.edu">nadin@stanford.edu</a>
                        </li>
                    </ul>
                    <br>
                    <ul class="list-inline">
                        <li>
                            <a href="#"><i class="fa fa-facebook fa-fw fa-2x"></i></a>
                        </li>
                        <li>
                            <a href="#"><i class="fa fa-twitter fa-fw fa-2x"></i></a>
                        </li>
                        <li>
                            <a href="#"><i class="fa fa-dribbble fa-fw fa-2x"></i></a>
                        </li>
                    </ul>
                    <hr class="small">
                    <p class="text-muted">Copyright &copy; VolunTeach 2015</p>
                </div>
            </div>
        </div>
    </footer>
</body>
</html>